import type { TokenMap } from "@vte/core";

/**
 * 将 token 路径转换为合法的 TypeScript 标识符
 */
function pathToIdentifier(path: string): string {
  return path
    .split(".")
    .map((part, i) => {
      // 数字开头需要加下划线
      if (/^\d/.test(part)) {
        return `_${part}`;
      }
      return part;
    })
    .join(".");
}

/**
 * 从 tokenMap 生成 tokens.d.ts 类型声明文件
 */
export function generateTokensDts(map: TokenMap): string {
  const lines: string[] = [
    "// Auto-generated by @vte/compiler - DO NOT EDIT",
    "// This file provides TypeScript types for design tokens",
    "",
  ];

  // 收集所有路径
  const paths: string[] = [];
  for (const [path] of map) {
    paths.push(path);
  }

  // 按层级分组
  const groups: Record<string, string[]> = {};
  for (const path of paths) {
    const parts = path.split(".");
    const group = parts[0];
    if (!groups[group]) {
      groups[group] = [];
    }
    groups[group].push(path);
  }

  // 生成 TokenPaths 联合类型
  const pathLiterals = paths.map((p) => `  | "${p}"`).join("\n");
  lines.push("/** 所有合法的 token 路径 */");
  lines.push(`export type TokenPaths =`);
  lines.push(pathLiterals);
  lines.push(";");
  lines.push("");

  // 生成 TokenValue 类型
  lines.push("/** Token 值的类型 */");
  lines.push("export type TokenValue = string | number;");
  lines.push("");

  // 生成 TokenMap 类型
  lines.push("/** Token 映射类型 */");
  lines.push("export interface TokenMap {");
  for (const path of paths) {
    const identifier = pathToIdentifier(path);
    const token = map.get(path);
    const value = token?.value ?? "";
    // 字面量类型
    lines.push(`  "${path}": "${value}";`);
  }
  lines.push("}");
  lines.push("");

  // 生成嵌套的 token 类型
  lines.push("/** 嵌套的 token 类型 */");
  lines.push("export interface Tokens {");

  for (const [group, groupPaths] of Object.entries(groups)) {
    lines.push(`  ${group}: {`);

    // 获取该组下的所有子路径
    const subPaths = groupPaths
      .filter((p) => p.split(".").length > 2)
      .sort();

    // 按第二层分组
    const subGroups: Record<string, string[]> = {};
    for (const p of subPaths) {
      const parts = p.split(".");
      const subGroup = parts[1];
      if (!subGroups[subGroup]) {
        subGroups[subGroup] = [];
      }
      subGroups[subGroup].push(p);
    }

    // 如果没有子组，直接列出叶子节点
    if (Object.keys(subGroups).length === 0) {
      for (const p of groupPaths) {
        const token = map.get(p);
        if (token && token.refs.length === 0) {
          lines.push(`    "${p.split(".").pop()}": "${token.value}";`);
        }
      }
    } else {
      for (const [subGroup, subGroupPaths] of Object.entries(subGroups)) {
        // 检查是否有更深层级
        const hasDeeper = subGroupPaths.some((p) => p.split(".").length > 3);

        if (hasDeeper) {
          lines.push(`    ${subGroup}: {`);
          for (const p of subGroupPaths) {
            const token = map.get(p);
            if (token && token.refs.length === 0) {
              const leaf = p.split(".").pop();
              lines.push(`      "${leaf}": "${token.value}";`);
            }
          }
          lines.push(`    };`);
        } else {
          for (const p of subGroupPaths) {
            const token = map.get(p);
            if (token && token.refs.length === 0) {
              const leaf = p.split(".").pop();
              lines.push(`    "${leaf}": "${token.value}";`);
            }
          }
        }
      }
    }

    lines.push(`  };`);
  }

  lines.push("}");
  lines.push("");

  // 生成常量值
  lines.push("/** Token 常量值 */");
  lines.push("export const tokens = {");

  for (const [group, groupPaths] of Object.entries(groups)) {
    lines.push(`  ${group}: {`);

    const subPaths = groupPaths
      .filter((p) => p.split(".").length > 2)
      .sort();

    const subGroups: Record<string, string[]> = {};
    for (const p of subPaths) {
      const parts = p.split(".");
      const subGroup = parts[1];
      if (!subGroups[subGroup]) {
        subGroups[subGroup] = [];
      }
      subGroups[subGroup].push(p);
    }

    if (Object.keys(subGroups).length === 0) {
      for (const p of groupPaths) {
        const token = map.get(p);
        if (token && token.refs.length === 0) {
          lines.push(`    "${p.split(".").pop()}": "${token.value}",`);
        }
      }
    } else {
      for (const [subGroup, subGroupPaths] of Object.entries(subGroups)) {
        const hasDeeper = subGroupPaths.some((p) => p.split(".").length > 3);

        if (hasDeeper) {
          lines.push(`    ${subGroup}: {`);
          for (const p of subGroupPaths) {
            const token = map.get(p);
            if (token && token.refs.length === 0) {
              const leaf = p.split(".").pop();
              lines.push(`      "${leaf}": "${token.value}",`);
            }
          }
          lines.push(`    },`);
        } else {
          for (const p of subGroupPaths) {
            const token = map.get(p);
            if (token && token.refs.length === 0) {
              const leaf = p.split(".").pop();
              lines.push(`    "${leaf}": "${token.value}",`);
            }
          }
        }
      }
    }

    lines.push(`  },`);
  }

  lines.push("} as const;");
  lines.push("");

  return lines.join("\n");
}
