import type { Plugin, ViteDevServer } from "vite";
import type { ResolvedConfig } from "vite";
import { parse } from "@vue/compiler-sfc";
import path from "path";
import fs from "fs";
import MagicString from "magic-string";
import { parseTokens, type TokenMap, toCssVarName } from "@vte-js/core";
import {
  type Platform,
  type PlatformAdapter,
  getPlatformAdapter,
} from "./codegen/index.js";
import { findSimilarTokens, formatTokenError } from "./similar.js";

export interface VtePluginOptions {
  tokenFile?: string;
  platform?: Platform;
  /** CSS 变量前缀（默认 "vte"，生成 --vte-{path}） */
  cssPrefix?: string;
  /** 构建时自动生成的文件配置 */
  output?: {
    /** 是否生成 tokens.d.ts */
    types?: boolean;
    /** 是否生成 tokens.css */
    css?: boolean;
    /** 是否生成 tokens.agent.json */
    agentJson?: boolean;
    /** 输出文件前缀（默认 "tokens"） */
    prefix?: string;
  };
  /** Sourcemap 配置 */
  sourcemap?: boolean | "inline" | "hidden";
}

export default function vtePlugin(options: VtePluginOptions = {}): Plugin {
  const platform: Platform = options.platform ?? "web";
  const cssPrefix: string = options.cssPrefix ?? "vte";
  const sourcemapOption = options.sourcemap ?? true;
  const outputOptions = {
    types: true,
    css: true,
    agentJson: true,
    prefix: "tokens",
    ...options.output,
  };
  let adapter: PlatformAdapter;

  let config: ResolvedConfig;
  let tokenMap: TokenMap | null = null;
  let cssVarBlock: string | null = null;
  let tokenFilePath: string | null = null;
  let server: ViteDevServer | null = null;

  function getTokenFilePath(root: string): string {
    if (options.tokenFile) {
      return path.resolve(root, options.tokenFile);
    }
    const candidates = [
      "design-tokens.ts",
      "tokens.ts",
      "src/design-tokens.ts",
      "src/tokens.ts",
    ];
    for (const candidate of candidates) {
      const p = path.resolve(root, candidate);
      if (fs.existsSync(p)) return p;
    }
    throw new Error(
      "[VTE] Cannot find design tokens file. " +
        `Looked for: ${candidates.join(", ")}. ` +
        "Set tokenFile option to specify custom path.",
    );
  }

  async function loadTokenMap(root: string): Promise<TokenMap> {
    const filePath = getTokenFilePath(root);
    tokenFilePath = filePath;
    tokenMap = await parseTokens(filePath);
    cssVarBlock = adapter.generateVars(tokenMap);
    return tokenMap;
  }

  async function reloadTokenMap(): Promise<void> {
    if (!config) return;
    try {
      const oldSize = tokenMap?.size ?? 0;
      await loadTokenMap(config.root);
      const newSize = tokenMap?.size ?? 0;

      console.log(`[VTE] Token map reloaded: ${oldSize} → ${newSize} tokens`);

      if (server) {
        server.ws.send({ type: "full-reload" });
      }
    } catch (e) {
      console.error("[VTE] Failed to reload token map:", e);
      // Send error to client for better DX
      if (server) {
        server.ws.send({
          type: "error",
          err: {
            message: `[VTE] Token reload failed: ${(e as Error).message}`,
            stack: (e as Error).stack ?? "",
          },
        });
      }
    }
  }

  /**
   * 生成 tokens 文件
   */
  async function generateTokenFiles(): Promise<void> {
    if (!config || !tokenMap) return;

    const outDir = config.build.outDir;
    const prefix = outputOptions.prefix;

    try {
      // 生成 tokens.css
      if (outputOptions.css && cssVarBlock) {
        const cssPath = path.join(outDir, `${prefix}.css`);
        fs.mkdirSync(path.dirname(cssPath), { recursive: true });
        fs.writeFileSync(cssPath, `/* Auto-generated by VTE - DO NOT EDIT */\n${cssVarBlock}\n`);
        console.log(`[VTE] Generated: ${cssPath}`);
      }

      // 生成 tokens.d.ts
      if (outputOptions.types) {
        const dtsPath = path.join(outDir, `${prefix}.d.ts`);
        fs.mkdirSync(path.dirname(dtsPath), { recursive: true });
        const dtsContent = generateDts(tokenMap);
        fs.writeFileSync(dtsPath, dtsContent);
        console.log(`[VTE] Generated: ${dtsPath}`);
      }

      // 生成 tokens.agent.json
      if (outputOptions.agentJson) {
        const agentPath = path.join(outDir, `${prefix}.agent.json`);
        fs.mkdirSync(path.dirname(agentPath), { recursive: true });
        const agentJson = generateAgentJson(tokenMap);
        fs.writeFileSync(agentPath, JSON.stringify(agentJson, null, 2));
        console.log(`[VTE] Generated: ${agentPath}`);
      }
    } catch (e) {
      console.error("[VTE] Failed to generate token files:", e);
    }
  }

  /**
   * 生成 TypeScript 类型声明
   */
  function generateDts(map: TokenMap): string {
    const lines: string[] = [
      "// Auto-generated by VTE - DO NOT EDIT",
      "",
      "/** 所有合法的 token 路径 */",
      "export type TokenPaths =",
    ];

    const paths: string[] = [];
    for (const [path] of map) {
      paths.push(`  | "${path}"`);
    }
    lines.push(paths.join("\n"));
    lines.push(";");
    lines.push("");
    lines.push("/** Token 值的类型 */");
    lines.push("export type TokenValue = string | number;");
    lines.push("");

    // 生成 TokenMap 接口
    lines.push("/** Token 映射类型 */");
    lines.push("export interface TokenMap {");
    for (const [path, token] of map) {
      lines.push(`  "${path}": "${token.value}";`);
    }
    lines.push("}");
    lines.push("");

    // 生成常量
    lines.push("/** Token 常量值 */");
    lines.push("export const tokens: TokenMap = {");
    for (const [path, token] of map) {
      lines.push(`  "${path}": "${token.value}",`);
    }
    lines.push("};");

    return lines.join("\n");
  }

  /**
   * 生成 agent.json
   */
  function generateAgentJson(map: TokenMap) {
    const tokens: Record<string, any> = {};
    let primitives = 0;
    let references = 0;

    for (const [path, token] of map) {
      const isRef = token.refs.length > 0;
      if (isRef) {
        references++;
      } else {
        primitives++;
      }

      tokens[path] = {
        value: token.value,
        original: isRef ? token.raw : token.value,
        refs: token.refs,
        platform: {
          web: `var(${toCssVarName(path, cssPrefix)})`,
          mp: token.value,
          rn: token.value,
        },
      };
    }

    return {
      version: "1.0.0",
      generatedAt: new Date().toISOString(),
      platform,
      prefix: outputOptions.prefix,
      tokens,
      stats: {
        total: map.size,
        primitives,
        references,
      },
    };
  }

  return {
    name: "@vte-js/vite-plugin",
    enforce: "pre",

    configResolved(resolvedConfig) {
      config = resolvedConfig;
      adapter = getPlatformAdapter(platform, cssPrefix);
      console.log(`[VTE] Platform: ${platform}, CSS prefix: ${cssPrefix}`);
    },

    configureServer(_server) {
      server = _server;

      let reloadTimer: ReturnType<typeof setTimeout> | null = null;
      const DEBOUNCE_MS = 300;

      const scheduleReload = () => {
        if (reloadTimer) clearTimeout(reloadTimer);
        reloadTimer = setTimeout(() => {
          reloadTimer = null;
          reloadTokenMap();
        }, DEBOUNCE_MS);
      };

      const handleTokenFileChange = (file: string) => {
        if (tokenFilePath && path.resolve(file) === tokenFilePath) {
          console.log("[VTE] Token file changed, scheduling reload...");
          scheduleReload();
        }
      };

      _server.watcher.on("change", handleTokenFileChange);
      _server.watcher.on("add", handleTokenFileChange);
      _server.watcher.on("unlink", handleTokenFileChange);
    },

    async buildStart() {
      // 在构建开始时加载 token
      if (!config?.command || config.command !== "build") return;

      try {
        await loadTokenMap(config.root);
        console.log(`[VTE] Tokens loaded: ${tokenMap?.size ?? 0}`);
      } catch (e) {
        console.error("[VTE] Failed to load tokens:", e);
      }
    },

    async closeBundle() {
      // 在构建结束时生成 tokens 文件
      await generateTokenFiles();
    },

    async transform(code, id) {
      if (!id.endsWith(".vue")) return null;

      const { descriptor, errors } = parse(code, {
        filename: id,
        sourceMap: true,
      });

      if (errors.length > 0) {
        for (const err of errors) {
          console.error("[VTE] SFC parse error:", err);
        }
        return null;
      }

      const tokenStyles = descriptor.styles.filter(
        (s) => "token" in s.attrs || s.lang === "token",
      );

      if (tokenStyles.length === 0) return null;

      const map = await loadTokenMap(config.root);
      if (!adapter) return null;

      const s = new MagicString(code);

      // 收集所有合法的 token 路径，用于查找相似路径
      const validPaths = Array.from(map.keys());

      for (const styleBlock of tokenStyles) {
        const contentStart = styleBlock.loc.start.offset;
        const contentEnd = styleBlock.loc.end.offset;
        const replaced = adapter.replaceRefs(styleBlock.content, map);
        s.update(contentStart, contentEnd, replaced);

        // 检查未解析的 token 引用并发出警告
        const unresolvedTokens = findUnresolvedTokens(styleBlock.content, map);
        for (const token of unresolvedTokens) {
          const suggestions = findSimilarTokens(token, validPaths);
          const message = formatTokenError(token, suggestions);
          this.warn(message);
        }

        // 处理 <style token scoped> -> <style scoped> 或 <style token module> -> <style module>
        if (styleBlock.attrs.scoped !== undefined || styleBlock.attrs.module !== undefined) {
          const beforeContent = code.substring(0, contentStart);
          const styleTagStart = beforeContent.lastIndexOf("<style");
          if (styleTagStart !== -1) {
            const originalTag = code.substring(styleTagStart, contentStart);
            const isModule = styleBlock.attrs.module !== undefined;
            const targetAttr = isModule ? "module" : "scoped";

            const newTag = originalTag.replace(
              /<style\s+token([^>]*)>/,
              (_match, attrs: string) => {
                const cleanedAttrs = attrs
                  .replace(/\btoken\b/, "")
                  .replace(/\bscoped\b/, "")
                  .replace(/\bmodule\b/, "")
                  .replace(/\s+/g, " ")
                  .trim();
                return `<style ${targetAttr}${cleanedAttrs ? " " + cleanedAttrs : ""}>`;
              },
            );
            s.update(styleTagStart, contentStart, newTag);
          }
        }
      }

      // 注入变量定义
      if (cssVarBlock) {
        const cssVarStyle = `\n<style>\n${cssVarBlock}\n</style>`;
        const lastStyleEnd = code.lastIndexOf("</style>");
        if (lastStyleEnd !== -1) {
          const insertPos = lastStyleEnd + "</style>".length;
          s.appendLeft(insertPos, cssVarStyle);
        } else {
          s.append(cssVarStyle);
        }
      }

      // 生成 sourcemap
      const sourcemap = sourcemapOption
        ? s.generateMap({
            source: id,
            includeContent: true,
            hires: true,
          })
        : null;

      return {
        code: s.toString(),
        map: sourcemap,
      };
    },
  };
}

/**
 * 查找内容中未解析的 token 引用
 */
function findUnresolvedTokens(content: string, map: TokenMap): string[] {
  const unresolved: string[] = [];
  const regex = /\$([\w][\w.]*)/g;
  let match;

  while ((match = regex.exec(content)) !== null) {
    const tokenPath = match[1];
    if (!map.has(tokenPath)) {
      if (!unresolved.includes(tokenPath)) {
        unresolved.push(tokenPath);
      }
    }
  }

  return unresolved;
}
