import path from "path";
import fs from "fs";
import { parseTokens, toCssVarName } from "@vte-js/core";

type Platform = "web" | "mp" | "rn";

interface GenerateOptions {
  platform: Platform;
  output?: string;
  prefix?: string;
}

export async function generateCommand(file: string, options: GenerateOptions) {
  const filePath = path.resolve(process.cwd(), file);
  const { platform } = options;

  console.log(`\n🔧 Generating ${platform} code from: ${filePath}\n`);

  try {
    const map = await parseTokens(filePath);
    let output: string;

    switch (platform) {
      case "web":
        output = generateWeb(map, options.prefix);
        break;
      case "mp":
        output = generateMp(map);
        break;
      case "rn":
        output = generateRn(map);
        break;
      default:
        console.error(`❌ Unknown platform: ${platform}`);
        process.exit(1);
    }

    if (options.output) {
      const outputPath = path.resolve(process.cwd(), options.output);
      fs.mkdirSync(path.dirname(outputPath), { recursive: true });
      fs.writeFileSync(outputPath, output);
      console.log(`✅ Generated: ${outputPath}\n`);
    } else {
      console.log(output);
    }

    process.exit(0);
  } catch (e) {
    console.error(`\n❌ Error: ${(e as Error).message}\n`);
    process.exit(1);
  }
}

function generateWeb(map: Map<string, { path: string; value: string }>, cssPrefix: string = "vte"): string {
  const lines: string[] = [
    "/* Auto-generated by VTE CLI - DO NOT EDIT */",
    "",
    ":root {",
  ];

  for (const [tokenPath, token] of map) {
    const varName = toCssVarName(tokenPath, cssPrefix);
    lines.push(`  ${varName}: ${token.value};`);
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}

function generateMp(map: Map<string, { path: string; value: string }>): string {
  const lines: string[] = [
    "/* Auto-generated by VTE CLI - DO NOT EDIT */",
    "/* 小程序平台：直接内联值，不使用 CSS Variables */",
    "",
  ];

  for (const [tokenPath, token] of map) {
    lines.push(`/* ${tokenPath} = ${token.value} */`);
  }

  return lines.join("\n") + "\n";
}

function generateRn(map: Map<string, { path: string; value: string }>): string {
  const lines: string[] = [
    "// Auto-generated by VTE CLI - DO NOT EDIT",
    "import { StyleSheet } from 'react-native';",
    "",
    "export const tokens = {",
  ];

  // 按层级分组
  const groups: Record<string, Record<string, string>> = {};

  for (const [tokenPath, token] of map) {
    const parts = tokenPath.split(".");
    const group = parts[0];
    const key = parts.slice(1).join(".");

    if (!groups[group]) {
      groups[group] = {};
    }
    groups[group][key] = token.value;
  }

  for (const [group, tokens] of Object.entries(groups)) {
    lines.push(`  ${group}: {`);
    for (const [key, value] of Object.entries(tokens)) {
      const num = Number(value);
      const display = !isNaN(num) && value !== "" ? num : `"${value}"`;
      lines.push(`    "${key}": ${display},`);
    }
    lines.push(`  },`);
  }

  lines.push("};");
  lines.push("");
  lines.push("export const styles = StyleSheet.create(tokens);");

  return lines.join("\n") + "\n";
}
